### ISSUE TITLE
NTR: Request for S06 1. Shell length 

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#15]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>1. Shell length  <p><b>Definition</b><p> 1. The  longest dimension of the shell <p><H2> Optional </H2><p>

**Comment by roy-lowry** [comment]
I think this should be handled differently. See terms like BLENOX26 defined as 'The mean value of the longest dimension of the shell or body of the specified organism in the sample. This could refer to a single individual should the sample size be one.' If the taxon isn't defined then a 'biological entity specified elsewhere' structure is needed.

**Comment by roy-lowry** [comment]
If there is an issue where the animal length is different from the shell length then an S25 entry for the animal 'subcomponent shell' is needed.

**Comment by gwemon** [comment]
Thanks @roy-lowry I guess that this request came from a OBIS user where the biological entity is not stored in the P01 code but held elsewhere in the schema.

We have 3 options:

1. create a variant of the S25 code for biological entity specified elsewhere (http://vocab.nerc.ac.uk/collection/S25/current/BE007117/) but with component='shell' (http://vocab.nerc.ac.uk/collection/S12/current/S1239/)
2. ask if the user could use [Length of biological entity specified elsewhere](http://vocab.nerc.ac.uk/collection/P01/current/OBSINDLX/) - the definition of this P01 concept might need to be made more generic.
3. create a new S06 for the term "Length (shell)"

I think that in the present case I would advise to go for option 2 unless we can think of a situation where the length of a shelled organism is not the longest dimension of the shell unless otherwise specified.  

However, there are other situations when the decision is not so obvious. There are already a few S06 terms related to various biological length measurements (mainly referring to fish or bird biometrics) so I guess now might be a good time to review what has been done so far and decide how we should handle these kinds of measurements consistently in the future.

S0600015 | Length | The longest horizontal dimension of an object | 2006-02-17
S0600101 | Length (Standard Length) | A standard measurement used in biometric science, in particular fish biometrics. | 2017-11-30
S0600097 | Length (culmen) | A standard measurement in bird biometrics referring to the distance along the main axis of the upper margin of the beak or bill. | 2017-11-30
S0600261 | Length (fork length) | A standard body length measurement used in fish biometric studies for fishes with forked tails and taken as the distance measured from the tip of the snout in a straight line to the posterior end of the shortest caudal rays in the center of the fork. | 2020-11-26
S0600096 | Length (from the front of the eye to the tip of the telson) | The distance along the main axis between a point just in front of the eye and the end of the rear-most segment of the body of certain invertebrates (e.g. crustaceans). | 2017-11-29
S0600098 | Length (head) | A standard measurement used in biometric science, in particular bird biometrics. | 2017-11-30
S0600149 | Length (in digital image) | The longest horizontal dimension of an object captured in a digital image and normally expressed in number of pixels. | 2018-01-10
S0600095 | Length (metasome) | The distance along the main axis of the posterior region of the body of certain invertebrates. | 2017-11-29
S0600094 | Length (prosome) | The distance along the main axis of the anterior region of the body of certain invertebrates. | 2017-11-29
S0600263 | Length (second dorsal length) | A body length measurement used for ratfish in fish biometric studies and taken as the distance measured from the snout to the posterior edge of the posterior lobe of the second dorsal fin. | 2020-11-26
S0600099 | Length (tarsus) | A standard measurement used in biometric science, in particular bird biometrics. | 2017-11-30
S0600262 | Length (total length) | A standard body length measurement used in biometric studies and taken as the longest distance along the main axis. In fish biometrics, this is the distance from the tip of the snout in a straight line to the posterior end of the caudal fin. | 2020-11-26
S0600100 | Length (wing) | A standard measurement used in biometric science, in particular bird, fish or insect biometrics. | 2017-11-30

**Comment by mknottingham** [comment]
I am an OBIS user looking into this issue. We can use the length of biological entity specified elsewhere, but wanted to be clear the length referred to the shell, not including the soft tissue that may extend outside of the shell.

**Comment by gwemon** [comment]
Link to https://github.com/nvs-vocabs/S06/issues/16

**Comment by gwemon** [comment]
@mknottingham our proposal is to create new S25 biological entities concepts for measurements that target a specific well defined body part or "subcomponent" of an organism. This enables us to remain consistent with the logic established in the P01 semantic model and avoid overcomplicating the concepts held in S06. These body parts or "sub-components" are defined in the NVS collection [S12](https://vocab.nerc.ac.uk/collection/S12/current/). 
So for your requirement, we are proposing to create a new entry in S25 for "biological entity specified elsewhere [Subcomponent: shell]"
where "shell" is defined [here](https://vocab.nerc.ac.uk/collection/S12/current/S1239/)
We will then use this new S25 concept to create 2 new P01 codes:
One for "Length of biological entity specified elsewhere [Subcomponent: shell]" and the other one for "Dry weight of biological entity specified elsewhere [Subcomponent: shell]"
Any issues, please let me know.

Note that this means that we will need to revise some of the S06 terms we created recently for the length of given fish and bird body parts. I will create a separate ticket for this and bring more people in the discussion.

**Comment by timvdstap** [comment]
Hi @gwemon ,

I like the proposed idea! Would I perhaps be able to tag along two new proposed terms to the NVS collection S12? These two body parts would be:  **mantle** and **bell**. Mantle length is often the length measured for Cephalopoda/Teuthida spp., whereas bell diameter is used when measuring jellyfish. Am I correct in thinking a similar classification or approach as with shell (length) can be adopted for these terms?

**Comment by gwemon** [comment]
Thanks @timvdstap. Yes please, make a request for the new terms under S12 using this [form](https://docs.google.com/forms/d/e/1FAIpQLSe-ZTKJZmNT5FmyPRFsPsNt2hpB_gb6MAmm7Zp-7GSMpn5NFA/viewform?entry.1396013310=S12); please provide definition and/or references to other vocabs/terminologies if you can or if appropriate.
If the proposal above gets the go-ahead, we will then create P01 codes of the form "Length of biological entity specified elsewhere [Subcomponent: bell]" and "Length of biological entity specified elsewhere [Subcomponent: mantle]"

**Comment by gwemon** [comment]
@timvdstap FYI see https://github.com/nvs-vocabs/S12/issues/5 and https://github.com/nvs-vocabs/S12/issues/4 for proposed definitions for mantle and bell terms in S12.

**Comment by timvdstap** [comment]
Hi @gwemon Yes those definitions would work for me with the abovementioned process (creating new P01 codes etc).

Thank you!

**Comment by timvdstap** [comment]
Hi all,

While I believe a P01 for mantle length has been created: https://vocab.nerc.ac.uk/collection/P01/current/DML1XX01/ , I don't see a term created yet for shell length, with a P01 term "Length of biological entity specified elsewhere [Subcomponent: shell]". Would you be able to tell me if it's still possible to create this term?

Thank you in advance!

**Comment by gwemon** [comment]
Thanks @timvdstap we will add it to P01.

**Comment by gwemon** [comment]
P01 created: http://vocab.nerc.ac.uk/collection/P01/current/SLSINDLX/
