### ISSUE TITLE
NTR: Request for Minor axis length (in digital image)

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/S06#22]
### Term name (PrefLabel)
Minor axis length (in digital image)
### Definition
The length of the secondary axis of the best fitting ellipse of an object captured in a digital image and normally expressed in µm or mm.
### Sources/references
Gorsky et. al. 2010, https://doi.org/10.1093/plankt/fbp124

### Mapping to external terminologies
http://vocab.nerc.ac.uk/collection/S06/current/S0600149/1/
### ORCID
https://orcid.org/0000-0003-3293-5612

**Comment by PatriciaCabrera** [comment]
Hello @gwemon, I have requested a series of terms related to image metadata here in S06. This terms are necessary for our work in the JERICO-S3 project to provide guidelines on plankton imagery metadata to be submitted to EMODnet Biology/EurOBIS. Are these terms foreseen to be created anytime soon?  Thank you! Patricia.

**Comment by gwemon** [comment]
Hi @PatriciaCabrera yes, they are on the backlog. We need to do some modelling work on them so that they fit our semantic model and can easily be re-used by others. S06 is only a component of a P01 parameter concept so when deciding on what needs to go in S06 we need to have an understanding of the full P01 concept. The P01 you associated with this S06 is not exactly related so I'll check this S06 request first and try to come up with some options for the corresponding P01 (which is the code you will need to use un the Measurement_type_id field in OBIS. I'll liaise with @danibodc on the other requests.

**Comment by PatriciaCabrera** [comment]
Hi @gwemon , Thank you for your quick answer and detailed explanation. This is very helpful. When you work on it and should need further information, please do not hesitate to contact me. Thanks!

**Comment by jiho** [comment]
In our last meeting, we decided that we would actually use the general Length and Width terms you have already created since this is "just" a specific way to measure width (and is actually not specific enough since there are many algorithms for ellipse fitting). So this one (and #23) could be closed.
Tagging @PatriciaCabrera for confirmation (but she's on leave currently).

**Comment by PatriciaCabrera** [comment]
@gwemon , @jiho , this can be closed to, and we will use this instead: http://vocab.nerc.ac.uk/collection/P01/current/WDPIXEL1/
