### ISSUE TITLE
NTR: Request for Mayor axis length (in digital image)

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/S06#23]
### Term name (PrefLabel)
Mayor axis length (in digital image)
### Definition
The length of the primary axis of the best fitting ellipse of an object captured in a digital image and normally expressed in µm or mm.
### Sources/references
Gorsky et. al. 2010, https://doi.org/10.1093/plankt/fbp124

### Mapping to external terminologies
http://vocab.nerc.ac.uk/collection/S06/current/S0600149/1/
### ORCID
https://orcid.org/0000-0003-3293-5612

**Comment by jiho** [comment]
In our last meeting, we decided that we would actually use the general Length and Width terms you have already created since this is "just" a specific way to measure length (and is actually not specific enough since there are many algorithms for ellipse fitting). So this one (and #22) could be closed.
Tagging @PatriciaCabrera for confirmation (but she's on leave currently).

**Comment by PatriciaCabrera** [comment]
@jiho,M @gwemon , Yes, I agree to close this one, and we use instead: http://vocab.nerc.ac.uk/collection/P01/current/LGPIXEL1/
