### ISSUE TITLE
NTR: Request for Width (in digital image)

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/S06#35]
### Term name (PrefLabel)
Width (in digital image) of biological entity specified elsewhere
### Definition
The width of the digital representation of an organism in a digital image measured in number of pixels.
### Sources/references
This submission is related to the existing term: Length (in digital image) of biological entity specified elsewhere, http://vocab.nerc.ac.uk/collection/S06/current/S0600149/

### ORCID
https://orcid.org/0000-0003-3293-5612

**Comment by gwemon** [comment]
@PatriciaCabrera Sorry it took so long! I kept wanting to go back and reevaluate the decision of how to model this kind of parameters in the semantic model but I am running out of time. I decided to go along with the decision taken in 2018 and created the width equivalent to http://vocab.nerc.ac.uk/collection/S06/current/S0600149/ in order to create the P01 combination you need.

**Comment by gwemon** [comment]
NTR linked to https://github.com/nvs-vocabs/P01/issues/75

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600276/
