### ISSUE TITLE
NTR: Precaudal Length [BODCNVS-1901]

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/S06#82]
### Term name (PrefLabel)
Precaudal Length
### Definition
A standard body length measurement used in fish biometric studies for fishes and taken as the distance measured from the tip of the snout in a straight line to the caudal peduncle. The biological entity is identified elsewhere in the data schema.
### Sources/references
[Please enter a link to a reference source]

**Comment by gwemon** [comment]
Hi @roswri  We already have some standard lengths terms in S06 and I would stay consistent with the structure we adopted (as in e.g. http://vocab.nerc.ac.uk/collection/S06/current/S0600096/). 

So would recommend a S06 preferred label of the form:  Length (precaudal)

And, because this is a S06 request and not a P01 request, I would not say anything about the biological entity (this will need to go in the P01 description if that is the case). So definition becomes: "A standard body length measurement used in fish biometric studies taken as the distance measured from the tip of the snout in a straight line to the caudal peduncle."

**Comment by gwemon** [comment]
New term S0600317	Length (precaudal) Queued for publication

**Comment by roswri** [comment]
Term live:
https://vocab.nerc.ac.uk/collection/S06/current/S0600317/
